name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why?
  - type: textarea
    id: extra
    attributes:
      label: Additional context
